### ISSUE TITLE
Unable to parse: `//=`

### ISSUE THREAD

**Issue by Chi-EEE** [seaofvoices/darklua#200] opened 2024-06-11 23:43 UTC
Command:
```
darklua process test.lua test.output.lua
```

Example:
- test.lua
```lua
local a = 100
a //= 9
print(a)
```

Error:
```
-> unable to parse `test.lua`: error occurred while creating ast: unexpected token `a`. (starting from line 2, character 1 and ending on line 2, character 2)
additional information: leftover token
```

**Comment by Chi-EEE** [comment] 2024-06-11 23:55
https://github.com/Kampfkarren/full-moon/issues/292

**Comment by jeparlefrancais** [comment] 2024-06-13 17:45
Hello 👋 You're right that I am waiting for a new full-moon release to support this syntax. I'll close this issue as it is a duplicate of #153

**Closed by jeparlefrancais** 2024-06-13 17:45 UTC
