### ISSUE TITLE
thread 'main' has overflowed its stack

### ISSUE THREAD

**Issue by ActualMasterOogway** [seaofvoices/darklua#205] opened 2024-07-07 11:31 UTC
I do not know what causes the issue in the file.
[Library.zip](https://github.com/user-attachments/files/16118977/Library.zip)
Sorry for uploading it as a zip, github doesnt allow `.luau` files

Using [darklua v0.13.1](https://github.com/seaofvoices/darklua/releases/tag/v0.13.1)

**Comment by jeparlefrancais** [comment] 2024-07-08 13:19
Thanks for sending a repro! I'll close the issue though as it is a duplicate of https://github.com/seaofvoices/darklua/issues/125

Full-moon has been updated so hopefully this will get fix very soon 🚀

**Closed by jeparlefrancais** 2024-07-08 13:19 UTC
